/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package namaanda.view;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import namaanda.util.Koneksi;

/**
 *
 * @author Lintanhg
 */
public class TampiBarangView extends javax.swing.JFrame {
    Koneksi koneksi = new Koneksi();
    /**
     * Creates new form TampilTemanView
     */
    public TampiBarangView() {
        initComponents();
        koneksi.koneksiDatabase();
        dataTable();
    }
    private void enableTrue(){
        jTextAreaAlamat.setEnabled(true);
        jTextFieldNama.setEnabled(true);
        jTextFieldNope.setEnabled(true);
        jButton1.setEnabled(true);
        jButton2.setEnabled(true);
    }
    
    private void enableFalse(){
        jTextAreaAlamat.setEnabled(false);
        jTextFieldNama.setEnabled(false);
        jTextFieldNope.setEnabled(false);
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
    }
    
    private void bersih(){
        jTextFieldId.setText("");
        jTextFieldNama.setText("");
        jTextFieldNope.setText("");
        jTextAreaAlamat.setText("");
    }

        private void dataTable(){
        DefaultTableModel tabel = new DefaultTableModel();
        
        tabel.addColumn("Id");
        tabel.addColumn("Kode Barang");
        tabel.addColumn("Nama Barang");
        tabel.addColumn("Jumlah Barang");
        
        jTable1.setModel(tabel);
        try {
            String sql = "select * from tbl_barang";
            
            ResultSet res = koneksi.state.executeQuery(sql);
            while(res.next()){
                tabel.addRow(new Object[]{
                    res.getString("id"),
                    res.getString("kode"),
                    res.getString("nama_barang"),
                    res.getString("qty")
                });
                jTable1.setModel(tabel);
                
            }
        } catch (SQLException eek) {
            System.err.println("SQLException:"+eek.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldNope = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaAlamat = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNama = new javax.swing.JTextField();
        jTextFieldId = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextFieldNope.setEnabled(false);

        jTextAreaAlamat.setColumns(20);
        jTextAreaAlamat.setLineWrap(true);
        jTextAreaAlamat.setRows(5);
        jTextAreaAlamat.setEnabled(false);
        jScrollPane2.setViewportView(jTextAreaAlamat);

        jLabel1.setText("id :");

        jButton1.setText("Ubah");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Hapus");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Qty");

        jButton3.setText("Baru");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("Kode :");

        jLabel3.setText("Nama :");

        jTextFieldNama.setEnabled(false);

        jTextFieldId.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldNope, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldNope, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String id = jTextFieldId.getText();//inisialiasi jTextFieldID menjadi id
        String nama = jTextFieldNama.getText();//inisialiasi jTextFieldNama menjadi nama
        String nope = jTextFieldNope.getText();//inisialiasi jTextFieldNope menjadi nope
        String alamat = jTextAreaAlamat.getText();//inisialiasi jTextAreaAlamat menjadi alamat

        try {
            koneksi.koneksiDatabase();//memanggil koneksiDatabase dari kelas Koneksi
            String kueriEdit = "update tbl_mahasiswa set nama ='"+nama+"', nope ='"+nope+"', alamat='"+alamat+"' where id='"+id+"'";//inisialiasi kueri untuk mengedit menjadi kueriEdit, "ubdate nama_tabel set" adalah perintah untuk mengedit sebuah data di dalam database
            koneksi.state.executeUpdate(kueriEdit);//menjalankan kueri edit
            dataTable();//memanggil dataTable() untuk refresh table
            JOptionPane.showMessageDialog(null, "Data Berhasil di ubah");//Pemberitahuan data telah di edit
        } catch (SQLException ex) {
            System.out.println("Error : "+ex);
        }
        bersih();
        enableFalse();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int pilihan = JOptionPane.showConfirmDialog(null,"Apakah anda ingin menghapus?","Keterangan",JOptionPane.YES_NO_OPTION);//inisialiasi pilihan untuk menghapus
        if(pilihan==JOptionPane.YES_NO_OPTION){//jika pilihan YES maka data akan di eksekusi, apabila no maka perintah di bawah tidak akan dijalankan
            String id = jTextFieldId.getText();//Inisialisasi jTextFieldID menjadi id
            try {
                String kueriHapus = "delete from tbl_barang where id='"+id+"'";//inisialiasi kueri untuk menghapus menjadi kueriHapus, "delete from" adalah perintah untuk menghapus sebuah data di dalam database
                koneksi.state.executeUpdate(kueriHapus);//menjalankan kueri hapus
                dataTable();//memanggil dataTable untuk merefresh data
                JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus..");//pemberitahuan ketika data telah terhapus

            } catch (SQLException ex) {
                System.err.println("Error : "+ex);
            }
            bersih();
            enableFalse();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int table = jTable1.getSelectedRow(); //inisialiasi jTable1.getSelectedRow() untuk mendapatkan Baris yang nantinya akan di panggil
        //mengambil data dari table
        String ambilID = jTable1.getValueAt(table, 0).toString(); //table yang tadi kita insialisasi akan diletakkan untuk baris dan kolom, sehingga data yang di pilih akan di letakkan pada jTextField yang dipilih
        String ambilNama = jTable1.getValueAt(table, 1).toString();
        String ambilNope = jTable1.getValueAt(table, 2).toString();
        String ambilAlamat = jTable1.getValueAt(table, 3).toString();

        enableTrue();

        jTextFieldId.setText(ambilID);//meletakkan data dari jTable1.getValueAt(table, 0).toString() ke dalam jTextFieldID
        jTextFieldNama.setText(ambilNama);
        jTextFieldNope.setText(ambilNope);
        jTextAreaAlamat.setText(ambilAlamat);
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TampiBarangView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TampiBarangView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TampiBarangView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TampiBarangView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TampiBarangView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextAreaAlamat;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldNama;
    private javax.swing.JTextField jTextFieldNope;
    // End of variables declaration//GEN-END:variables
}
